In [11]:
import numpy as np
# creating an array
a = np.array([[1,3,5,2], [2,6,4,9],[1, 7, 8, 9]])
print(a)
print(type(a))
print(a.shape)

#slicing an array with first two rows and and 1st and 2nd column
print()
b = a[:2,1:3]
print(b)
#slicing an array with last two rows columns
c = a[-2:, -2:]
print(c)

print(b[0,0])

[[1 3 5 2]
 [2 6 4 9]
 [1 7 8 9]]
<class 'numpy.ndarray'>
(3, 4)

[[3 5]
 [6 4]]
[[4 9]
 [8 9]]
3
