In [5]:
import numpy as np
a = np.array([[1,2,3], [4,5,6], [1,1,6], [2,1,3]])
print(a)
print()
boln_indx = (a>2) 
print(boln_indx)
print()
print(a[boln_indx])
print()
print(a[a>2])

[[1 2 3]
 [4 5 6]
 [1 1 6]
 [2 1 3]]

[[False False  True]
 [ True  True  True]
 [False False  True]
 [False False  True]]

[3 4 5 6 6 3]

[3 4 5 6 6 3]
