In [10]:
import numpy as np
# creating an array
a = np.array([[1,3,5,2], [2,6,4,9],[1, 7, 8, 9]])
print(a)
print()

print(a[[2,1,2],[0,1,1]])
print(np.array([a[2,0], a[1,1], a[2,1]]))

print()

#creating array of indices
b = np.array([1,2,0])
print(a[np.arange(3), b]) #selecting element of each row using indices of b

print()
a[np.arange(3), b] +=3    # Mutate one element from each row of a using the indices in b

print(a)

[[1 3 5 2]
 [2 6 4 9]
 [1 7 8 9]]

[1 6 7]
[1 6 7]

[3 4 1]

[[1 6 5 2]
 [2 6 7 9]
 [4 7 8 9]]
