In [10]:
import numpy as np
# creating an array
a = np.array([[1,3,5,2], [2,6,4,9],[1, 7, 8, 9]])
print(a)

print()
# Slicing with integer
rowR1 = a[2, : ]  #slicing row with Rank2
print(rowR1)
print(rowR1.shape)
print()
col = a[:, 0]      #slicing column with rank 0
print(col)
print(col.shape)
print()
col2 = a[:, 1:2]   #slicing column with rank 1
print(col2)
print(col2.shape)


[[1 3 5 2]
 [2 6 4 9]
 [1 7 8 9]]

[1 7 8 9]
(4,)

[1 2 1]
(3,)

[[3]
 [6]
 [7]]
(3, 1)
