In [20]:
import numpy as np
a = np.arange(10,100,5)
print(a)

a = a.reshape(6,3)
print(a)

print()

for i in np.nditer(a):  #ierator on elements of a
    print(i, end = " ")

print()
print()
b = a.T                 #Tansposing matrix a and storing in b
print(b)

print()
c = b.copy(order = 'C')  #Making copy of c with order C
print(c)
for i in np.nditer(c):
    print(i, end = " ")  #Iterating with order C
    
print()
d = b.copy(order = 'F')
print(d)
for i in np.nditer(d):   #Iterating with order F
    print(i, end = " ")

[10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]
[[10 15 20]
 [25 30 35]
 [40 45 50]
 [55 60 65]
 [70 75 80]
 [85 90 95]]

10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95 

[[10 25 40 55 70 85]
 [15 30 45 60 75 90]
 [20 35 50 65 80 95]]

[[10 25 40 55 70 85]
 [15 30 45 60 75 90]
 [20 35 50 65 80 95]]
10 25 40 55 70 85 15 30 45 60 75 90 20 35 50 65 80 95 
[[10 25 40 55 70 85]
 [15 30 45 60 75 90]
 [20 35 50 65 80 95]]
10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95 