In [2]:
import numpy as np

# basic broadcast program
a = np.array([[0,1,2,3],[2,3,4,5],[10,20,30,40],[30,40,50,60]])
b = np.array([10,5,10,5])
print("first array")
print(a)
print()
print("second array")
print(b)
print()
print("Broadcasting")

c = a + b
print(c)

first array
[[ 0  1  2  3]
 [ 2  3  4  5]
 [10 20 30 40]
 [30 40 50 60]]

second array
[10  5 10  5]

Broadcasting
[[10  6 12  8]
 [12  8 14 10]
 [20 25 40 45]
 [40 45 60 65]]
