In [9]:
import numpy as np
a = np.zeros((4,4))  #creates array of size 4 * 4 of all zeros
print(a)

print()

b = np.ones((2,3))   #creates array of size 2 * 3 of all ones
print(b)

print()

c = np.full((3,3), 5) #creates array of size 3 * 3 of all fives
print(c)

print()

d = np.eye(2)         #creates array of size 2 * 2 identity matrix
print(d)

print()

e = np.random.random((3, 2))  #creates array of size 3 * 2 of random numbers
print(e)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

[[1. 1. 1.]
 [1. 1. 1.]]

[[5 5 5]
 [5 5 5]
 [5 5 5]]

[[1. 0.]
 [0. 1.]]

[[0.10985109 0.6846686 ]
 [0.70783835 0.29008895]
 [0.01697986 0.89438212]]
