In [7]:
# basic mathematical operation
import numpy as np
a = np.array([[1,2],[4,6], [11,54]])
b = np.array([[3,7], [45,22], [6,9]])
print(a+b)
print("addition using numpy add function")
print(np.add(a,b))          #addition using numpy add function
print()
print(a-b)
print("subtraction using numpy subtract function")
print(np.subtract(a,b))     #subtraction using numpy subtract function
print()
print(a*b)
print("multiplication using numpy multiply function")
print(np.multiply(a,b))     #multiplication using numpy multiply function
print() 
print(a/b)
print("Division using numpy divide function")
print(np.divide(a,b))       #division using numpy divide function
print()
print("square root using numpy sqrt function")
print(np.sqrt(a))           #square root using numpy sqrt function

[[ 4  9]
 [49 28]
 [17 63]]
addition using numpy add function
[[ 4  9]
 [49 28]
 [17 63]]

[[ -2  -5]
 [-41 -16]
 [  5  45]]
subtraction using numpy subtract function
[[ -2  -5]
 [-41 -16]
 [  5  45]]

[[  3  14]
 [180 132]
 [ 66 486]]
multiplication using numpy multiply function
[[  3  14]
 [180 132]
 [ 66 486]]

[[0.33333333 0.28571429]
 [0.08888889 0.27272727]
 [1.83333333 6.        ]]
Division using numpy divide function
[[0.33333333 0.28571429]
 [0.08888889 0.27272727]
 [1.83333333 6.        ]]

square root using numpy sqrt function
[[1.         1.41421356]
 [2.         2.44948974]
 [3.31662479 7.34846923]]
