In [17]:
import numpy as np
x = np.random.normal(size = 5)
print(x)
print()
# random number with size 10 in range 10-50 
print("random number with size 10 in range 10-50")
y = np.random.randint(low = 10, high = 50, size = 10)
print(y)
print()
#random array of size 3*3*3
print("random array of size 3*3*3")
a = np.random.random(3*3*3)
print(a)
print()
#finding minimum and maximum from array
print("finding minimum and maximum from array")
b = np.min(a)
print("minimum value of array is",b)
c = np.max(a)
print("maximum value of array is",c)
print()
"""Write a Python program to create a random 10x4 array and 
extract the first five rows of the array and store them into a variable."""
randMatrix = np.random.rand(10,4)
print(randMatrix)
print("First five rows of above array")
firstFive = randMatrix[:5, :]
print(firstFive)


[-0.97671318  0.7495893   0.11467499 -1.3952103  -0.85303472]

random number with size 10 in range 10-50
[16 13 20 32 21 36 32 38 23 24]

random array of size 3*3*3
[0.24975834 0.04798796 0.09307773 0.57117292 0.85082957 0.56188375
 0.62496193 0.81141081 0.1591034  0.72235565 0.88475321 0.26729766
 0.50240069 0.30334654 0.53251113 0.4585112  0.56250927 0.65263687
 0.87241512 0.9058036  0.85594817 0.66646616 0.53202662 0.94282142
 0.00777311 0.05881388 0.32149348]

finding minimum and maximum from array
minimum value of array is 0.007773105933218227
maximum value of array is 0.942821420184294

[[5.58181100e-02 6.15186185e-01 4.52080768e-01 4.70233321e-04]
 [3.90734343e-01 5.95172805e-01 1.46214101e-01 6.83692789e-02]
 [8.36251321e-01 1.86633814e-01 8.55269477e-01 1.07314853e-01]
 [8.82140472e-01 9.63944069e-01 5.85030843e-01 3.38232346e-01]
 [8.27903404e-01 6.05909965e-01 3.34524675e-02 2.78145252e-01]
 [1.20219457e-01 8.58756003e-01 1.04077487e-01 2.47426275e-01]
 [6.69158874e-01 4.771