In [4]:
import numpy as np
b = np.array([[3,7], [45,22], [6,9]])
print(b)
print()
print("after transpossing")
print(b.T)     #numpy uses T to transpose matrix

print()
# Note that taking the transpose of a rank 1 array does nothing:
b = np.array([1,2,3])
print(b)    # Prints "[1 2 3]"
print("after transpossing")
print(b.T)  # Prints "[1 2 3]"

[[ 3  7]
 [45 22]
 [ 6  9]]

after transpossing
[[ 3 45  6]
 [ 7 22  9]]

[1 2 3]
after transpossing
[1 2 3]
